# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "mad_chatter"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew Havens"]
  s.date = "2011-12-07"
  s.description = "Mad Chatter is a fun, easy to customize chat server, utilizing HTML 5 Web Sockets"
  s.email = "email@andrewhavens.com"
  s.executables = ["mad_chatter"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "CHANGELOG.txt",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "bin/mad_chatter",
    "lib/mad_chatter.rb",
    "lib/mad_chatter/action.rb",
    "lib/mad_chatter/actions/join.rb",
    "lib/mad_chatter/actions/rename.rb",
    "lib/mad_chatter/config.rb",
    "lib/mad_chatter/extensions.rb",
    "lib/mad_chatter/message.rb",
    "lib/mad_chatter/server.rb",
    "lib/mad_chatter/servers/em_websocket.rb",
    "lib/mad_chatter/servers/juggernaut.rb",
    "lib/mad_chatter/servers/websocket_rack.rb",
    "lib/mad_chatter/users.rb",
    "lib/mad_chatter/version.rb",
    "templates/config.yml",
    "templates/extensions.rb",
    "templates/web/index.html",
    "templates/web/javascript.js",
    "templates/web/stylesheets/reset.css",
    "templates/web/stylesheets/styles.css",
    "test/helper.rb",
    "test/test_mad_chatter.rb"
  ]
  s.homepage = "http://github.com/andrewhavens/mad_chatter"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Mad Chatter is a fun, easy to customize chat server, utilizing HTML 5 Web Sockets"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<eventmachine>, ["= 0.12.10"])
      s.add_runtime_dependency(%q<em-websocket>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<eventmachine>, ["= 0.12.10"])
      s.add_dependency(%q<em-websocket>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<eventmachine>, ["= 0.12.10"])
    s.add_dependency(%q<em-websocket>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

